name: "CLA Assistant"
on:
  issue_comment:
    types: [created]
  pull_request:
    types: [opened,closed,synchronize]
    
jobs:
  CLAssistant:
    runs-on: ubuntu-latest
    steps:
    - name: "CLA Assistant"
      if: (github.event.comment.body == 'recheckcla' || github.event.comment.body == 'I have read the CLA Document and I hereby sign the CLA') || github.event_name == 'pull_request'
      # Test Release
      uses: cla-assistant/github-action@v1.0.0
      env: 
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with: 
        path-to-signatures: 'signatures/version1/cla.json'
        path-To-cladocument: 'https://github.com/alohr51-kabanero/cla-test/blob/1.0.0/cla.txt'
        branch: 'master'
        blockchain-storage-flag: false